theme: jekyll-theme-slate
title: My Personal User Manual
description: Welcome my Personal User Manual! If you'd like to create your own check out this [template](https://github.com/camin-mccluskey/Personal-User-Manual-Template).
